# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EeroCli < Formula
  desc "Command-line utility for controlling Eero mesh WiFi networks"
  homepage "https://github.com/dciobanu/eero-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dciobanu/eero-cli/releases/download/v1.1.0/eero-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "3bf920cef1f4377c2ae94cafac9af2ddafce689e630f84b1e4d29497e9ccd142"

      def install
        bin.install "eero-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dciobanu/eero-cli/releases/download/v1.1.0/eero-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "c245eab3b3c07a038eec3f5d7138d042f599985f7d49e48231e918728a7ae3f6"

      def install
        bin.install "eero-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/eero-cli/releases/download/v1.1.0/eero-cli_1.1.0_linux_amd64.tar.gz"
      sha256 "fae74c2e1de5488dad8b88e7b04895f6280f47ae46f85bf950dcd25e5b26b54e"
      def install
        bin.install "eero-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/eero-cli/releases/download/v1.1.0/eero-cli_1.1.0_linux_arm64.tar.gz"
      sha256 "5e521310a44caec40a10bf25566847aa792a5576a0fdbeba2055a74058484eae"
      def install
        bin.install "eero-cli"
      end
    end
  end

  test do
    system "#{bin}/eero-cli", "help"
  end
end
