# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HassCli < Formula
  desc "Command-line utility for controlling Home Assistant"
  homepage "https://github.com/dciobanu/hass-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.6.0/hass-cli_0.6.0_darwin_amd64.tar.gz"
      sha256 "dae0ac4fdea5da18ce40efe535d668d7bfccdf48a190175146333d8679ef8dfd"

      define_method(:install) do
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.6.0/hass-cli_0.6.0_darwin_arm64.tar.gz"
      sha256 "4942165113d09619f54a58feca1ea7efc8cbc7d9f92dafdd700ffc06be3f4821"

      define_method(:install) do
        bin.install "hass-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.6.0/hass-cli_0.6.0_linux_amd64.tar.gz"
      sha256 "196eab98356f39830d89f970f1d3f566a784b453918d7c0d5d91fab4e2dbb6a8"
      define_method(:install) do
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.6.0/hass-cli_0.6.0_linux_arm64.tar.gz"
      sha256 "cc7e032d35368ba50369f22384c4e7f78a3dfcf2de5df90e07c05ffc481f72cf"
      define_method(:install) do
        bin.install "hass-cli"
      end
    end
  end

  test do
    system "#{bin}/hass-cli", "help"
  end
end
