# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HassCli < Formula
  desc "Command-line utility for controlling Home Assistant"
  homepage "https://github.com/dciobanu/hass-cli"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.4.1/hass-cli_0.4.1_darwin_amd64.tar.gz"
      sha256 "5e4d9afa4b12d994ce60558402dda707e6bad763a0aee3c30b0bca82fbb78ca4"

      def install
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.4.1/hass-cli_0.4.1_darwin_arm64.tar.gz"
      sha256 "e3f1584cf73ac8871f65c821df82b5ff968cf12503f63a7b4358253374ba6761"

      def install
        bin.install "hass-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.4.1/hass-cli_0.4.1_linux_amd64.tar.gz"
      sha256 "016676a42213ae55b53855ad8a148865d57b0f8a21ae938d85e25749c0417681"
      def install
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.4.1/hass-cli_0.4.1_linux_arm64.tar.gz"
      sha256 "bc4a3faedf66dafb89244963e4558bc47eb7efea98fa435966662ebdb1fbfe56"
      def install
        bin.install "hass-cli"
      end
    end
  end

  test do
    system "#{bin}/hass-cli", "help"
  end
end
