# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HassCli < Formula
  desc "Command-line utility for controlling Home Assistant"
  homepage "https://github.com/dciobanu/hass-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.5.0/hass-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "69a03b25bd7c4fdd58f8d23b63ab86dc4e3d25b13cbab4cd95e0513e938e7e84"

      define_method(:install) do
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.5.0/hass-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "ef57291d8a21a441901e02dedd9c5deeeaf706abeb1d5e5f4867bd8a68132a3b"

      define_method(:install) do
        bin.install "hass-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.5.0/hass-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "c07d2dea13048b7c082bf2effd5ccc5a59eef428dbdf6bc2a8fb0688218bdf26"
      define_method(:install) do
        bin.install "hass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dciobanu/hass-cli/releases/download/v0.5.0/hass-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "c0efaf67bade78052fc04874312dcc12d7146018b91185c8c1f8dcd2cc010fb1"
      define_method(:install) do
        bin.install "hass-cli"
      end
    end
  end

  test do
    system "#{bin}/hass-cli", "help"
  end
end
